// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5IU4j3HoRFsEYgwyyO9jRT0i5bR-Eqzw',
    appId: '1:141063738181:web:812e75f47a300a4db6a42c',
    messagingSenderId: '141063738181',
    projectId: 'midterm-test-28caf',
    authDomain: 'midterm-test-28caf.firebaseapp.com',
    storageBucket: 'midterm-test-28caf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYSofb04QQhR45n8BwHlkcAxG_LTOMzKc',
    appId: '1:141063738181:android:17f2394cba2666ccb6a42c',
    messagingSenderId: '141063738181',
    projectId: 'midterm-test-28caf',
    storageBucket: 'midterm-test-28caf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeoPCIiMcm3yB4PwqIk75dX-qvHK9cIbI',
    appId: '1:141063738181:ios:fc664e1e58abd8fab6a42c',
    messagingSenderId: '141063738181',
    projectId: 'midterm-test-28caf',
    storageBucket: 'midterm-test-28caf.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeoPCIiMcm3yB4PwqIk75dX-qvHK9cIbI',
    appId: '1:141063738181:ios:fc664e1e58abd8fab6a42c',
    messagingSenderId: '141063738181',
    projectId: 'midterm-test-28caf',
    storageBucket: 'midterm-test-28caf.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5IU4j3HoRFsEYgwyyO9jRT0i5bR-Eqzw',
    appId: '1:141063738181:web:7cdd2f04d4208f3db6a42c',
    messagingSenderId: '141063738181',
    projectId: 'midterm-test-28caf',
    authDomain: 'midterm-test-28caf.firebaseapp.com',
    storageBucket: 'midterm-test-28caf.firebasestorage.app',
  );
}
